#!/usr/bin/env bash

read -e -p "Please enter the Instruct filename: " filename

#Poor attempt at making sure the input file was generated by InStruct
if grep -q "InStruct by Gao" $filename ; then
	echo "Processing..."
else
	echo "ERROR: Please check the input file,the format appears incorrect"
	exit 1
fi

#Get variables for program
chain_num=$(egrep -a "Chain Number=[0-9]+" $filename | egrep -o '[0-9]+')
num_ind=$(egrep -a "Population size=[0-9]+" $filename | egrep -o '[0-9]+')
num_loci=$(egrep -a "Number of loci=[0-9]+" $filename | egrep -o '[0-9]+')
k_value_max=$(egrep -a -A1 "Command line arguments" $filename | egrep -o "\-kv [0-9] [0-9]+" | egrep -o "[0-9]+$")

#Make directories to store files, unless they are already present
if [ ! -d qmatrix/ ]; then
	mkdir qmatrix
fi
if [ ! -d indruns/ ]; then
	mkdir indruns
fi

COUNTER=1
while [ $COUNTER -le $k_value_max ]; do
	cat $filename | tr -d '\000' | tr -d '\r' | grep -E -A $num_ind "Cluster $COUNTER$" > K${COUNTER}_Qmatrixes.txt
	((COUNTER++))
done

X=1
#If the number of chains is >2.
if [ $chain_num -gt 2 ]; then

	for i in `find . -maxdepth 1 -name "*Qmatrixes*.txt" |sort -V`; do
		new_num_ind1=$(expr 1 + $num_ind)
		sed -n "1, "$new_num_ind1"p" "$i" > K${X}_RUN1.txt
		new_num_ind1=$(expr 2 + $new_num_ind1) 
		new_num_ind2=$(expr "$num_ind" + "$new_num_ind1")
		sed -n ""$new_num_ind1", "$new_num_ind2"p" "$i" > K${X}_RUN2.txt
		Y=3
		while [ $chain_num -ge $Y ]; do
			new_num_ind1=$(expr 2 + "$num_ind" + $new_num_ind1) 
			new_num_ind2=$(expr "$num_ind" + "$new_num_ind1")
			sed -n ""$new_num_ind1", "$new_num_ind2"p" "$i" > K${X}_RUN${Y}.txt
			((Y++))
		done
		((X++))
	done

#If the number of chains used is 2
elif [ $chain_num = 2 ]; then
	for i in `find . -maxdepth 1 -name "*Qmatrixes*.txt" |sort -V`; do
		new_num_ind1=$(expr 1 + $num_ind)
		sed -n "1, "$new_num_ind1"p" "$i" > K${X}_RUN1.txt
		new_num_ind1=$(expr 2 + $new_num_ind1) 
		new_num_ind2=$(expr "$num_ind" + "$new_num_ind1")
		sed -n ""$new_num_ind1", "$new_num_ind2"p" "$i" > K${X}_RUN2.txt
		((X++))
	done

#If the number of chains used is 1
elif [ $chain_num = 1 ]; then
	for i in `find . -maxdepth 1 -name "*Qmatrixes*.txt" |sort -V`; do
		new_num_ind1=$(expr 1 + $num_ind)
		sed -n "1, "$new_num_ind1"p" "$i" > K${X}_RUN1.txt
		((X++))
	done
fi

#Cut runs to only the Q matrixes, basically removing un-needed columns
for i in K*_RUN*.txt; do
	cut -f 5- $i > $$
	mv $$ $i
	tail -n +2 $i > $$
	mv $$ $i
done

mv *Qmatrixes* qmatrix
mv *RUN* indruns

echo "Done"

###In the future
###Remove the grep search to check the input file and instead issue 
###tests on all of the variables (they should be integers). 